kind: pipeline
type: kubernetes
name: default

platform:
  arch: amd64

steps:
- name: build
  image: nginx
  commands:
    - cp -r /drone/src/. /usr/share/nginx/html
    - cd /usr/share/nginx/html

- name: publish
  image: plugins/docker
  settings:
    registry: localhost:32000
    repo: localhost:32000/cv-nginx
    tags: registry
