kind: pipeline
type: kubernetes
name: default

platform:
  arch: amd64

steps:
- name: build
  image: nginx
  commands:
    - cp -r /drone/src/. /usr/share/nginx/html
    - cd /usr/share/nginx/html

- name: publish
  image: plugins/docker
  settings:
    username: iamkimninja
    password: MW374fnny.d
    repo: iamkimninja/cv-nginx
    tags: latest

- name: Deploy app
  image: danielgormly/drone-plugin-kube:0.2.0
  settings:
    build_number: ${DRONE_BUILD_NUMBER}
    ca: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURBVENDQWVtZ0F3SUJBZ0lKQVBRYS9ONTh6WVNiTUEwR0NTcUdTSWIzRFFFQkN3VUFNQmN4RlRBVEJnTlYKQkFNTURERXdMakUxTWk0eE9ETXVNVEFlRncweU1EQTNNVEF4TURNMU5UUmFGdzB6TURBM01EZ3hNRE0xTlRSYQpNQmN4RlRBVEJnTlZCQU1NRERFd0xqRTFNaTR4T0RNdU1UQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQCkFEQ0NBUW9DZ2dFQkFNTCtSMHdSMWl1ZTdyNzVBR1dlczlsVGJQVkFLQm9VNWJEa2VKT1plcS9qRzVUdm14N3kKWEJmdHpVS0MvOWdIMWY2NUU3SUpxT00zNk5GVUp6UCs5U0hudWpjdHdmV3E4dGFHay8xQ2tpc0NxUzZPczNVTwp2M3dFUFlFeVVoZ0VqZUZFMlVpZTl3TEdwNmtFR0hmdDZsZnZETUMwdUVGNnNxRHlRN0dFWnAzWWNQTTRJMDJ6Ck1OMG5obUhVRGF5cEhFaFFlb1ZrQ1dYTktiL1VSR2ZPTnVHRkZncDdxSHJMOGVUbjY5N0wwQ3lsVlZGM0tSL3cKNkJYWlZWQWcxRkI0SnhZZllqR29aUXFOM0lqcWdHMUgzNytrL0xvTHVKY2kxcDhRMXNJVjRCMU9XaDlXNGxJNwpoV3c3UjcrUXFKUFRrOUZ4clFrWjk1UG0rT3ZydnNDSkIxY0NBd0VBQWFOUU1FNHdIUVlEVlIwT0JCWUVGR0R6CnBVNEpQU2wyeUtxNVZXSGF0YjcxNHRFTU1COEdBMVVkSXdRWU1CYUFGR0R6cFU0SlBTbDJ5S3E1VldIYXRiNzEKNHRFTU1Bd0dBMVVkRXdRRk1BTUJBZjh3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUE3MlYrYTZzTURSdTJpVgpScUJGL1Q4V3cyL2laQk1nVDBTWE5DSHV2a3lQQzM0S2Q3anIxTnpEYmdnNkNVME00NUVZNDRSck9tTHVra0d1CmZObGFNbmlSYmxqeG00Y3I0VElGbCsybzJiRFBXcEJwQ3FxSE56aWZhZ2ZzcWlTYkxQMElNSGNTdHVwNGRzTnIKbjhZVS9TaTZySUpIVXUxcVl4T1dFaGRmMnZYYnc0UXp6ZFZHYnhlclh0ekpGMTA2eit0Y3drMElldGw2aFV0dAoxQUNzczJXRDdhbEEyZUJxbVhFMWNKcmpyRkdFYitpMXRHMWg0cHNvSGxMbzREdmdwSUJMaXdxUWVzTERNUWQrClNPVTI1YmNXN2hXSkV5TkZmUE1jQmoyOGpRT2ptRXlHVytMcUVlU1VPa0c5RjZZZlpMdWhET1Z3dWRKZkJTQUoKL3hDU0E1Zz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://192.168.178.201:16443
    token: bWEyZU9DY0R2clY3dHdXLzliNU9SVjVrcDBPM3RiMGVOUUVmQXZwTk5JUT0K
    namespace: personal-space
    template: deployment.yaml
