kind: pipeline
type: kubernetes
name: default

platform:
  arch: amd64

steps:
- name: build
  image: nginx
  commands:
    - cp -r /drone/src/. /usr/share/nginx/html

- name: publish
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: iamkimninja/cv-nginx
    tags: latest

- name: deploy
  image: danielgormly/drone-plugin-kube:0.2.0
  settings:
    ca:
      from_secret: deploy_ca
    server:
      from_secret: deploy_server
    token:
      from_secret: deploy_token
    namespace: personal-space
    template: deployment.yaml
