kind: pipeline
type: kubernetes
name: default

platform:
  arch: amd64

steps:
- name: build
  image: nginx
  commands:
    - cp -r /drone/src/. /usr/share/nginx/html
    - cd /usr/share/nginx/html

- name: publish
  image: plugins/docker
  settings:
    username: iamkimninja
    password: MW374fnny.d
    repo: iamkimninja/cv-nginx
    tags: latest

- name: deploy
  image: image: danielgormly/drone-plugin-kube:0.2.0
  settings:
    kubernetes_server: https://kubernetes.iamkim.ninja
    kubernetes_token: bWEyZU9DY0R2clY3dHdXLzliNU9SVjVrcDBPM3RiMGVOUUVmQXZwTk5JUT0K
    template: deployment.yaml
