apiVersion: apps/v1
kind: Deployment
metadata:
  name: cv-nginx
  namespace: personal-space
  labels:
    app: cv-nginx
spec:
  selector:
    matchLabels:
      app: cv-nginx
  template:
    metadata:
      labels:
        app: cv-nginx
    spec:
      containers:
      - name: cv-nginx-container
        image: iamkimninja/cv-nginx:{{ build_number }}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
